# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRAEBCSycm-lOpVLslO8SabvAnXuEyhl
"""

# 1.To write a Python program to add two numbers entered by the user.

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

sum_result = num1 + num2

print("The sum is:", sum_result)

# 2.To write a Python program to interchange the values of two variables.

a = input("Enter the first value: ")
b = input("Enter the second value: ")

a, b = b, a

print("After swapping:")
print("First value =", a)
print("Second value =", b)

# 3.To write a Python program to find the largest among three numbers using conditional statements.

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

if num1 >= num2 and num1 >= num3:
    largest = num1
elif num2 >= num1 and num2 >= num3:
    largest = num2
else:
    largest = num3

print("The largest number is:", largest)

# 4.To write a Python program to check whether a given number is even or odd.

num = int(input("Enter a number: "))

if num % 2 == 0:
    print(num, "is an Even number.")
else:
    print(num, "is an Odd number.")

# 5.To write a Python program to determine whether a number is positive, negative, or zero.

num = float(input("Enter a number: "))

if num > 0:
    print("The number is Positive.")
elif num < 0:
    print("The number is Negative.")
else:
    print("The number is Zero.")

# 6.To write a Python program to check whether a given year is a leap year.

year = int(input("Enter a year: "))

if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
    print(year, "is a Leap Year.")
else:
    print(year, "is not a Leap Year.")

# 7.To write a Python program to perform basic arithmetic operations using operators.

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

print("Addition =", num1 + num2)
print("Subtraction =", num1 - num2)
print("Multiplication =", num1 * num2)

if num2 != 0:
    print("Division =", num1 / num2)
    print("Floor Division =", num1 // num2)
    print("Modulus =", num1 % num2)
else:
    print("Division, Floor Division, and Modulus cannot be performed (division by zero).")

print("Exponentiation =", num1 ** num2)

# 8.To write a Python program to display the multiplication table of a given number.

num = int(input("Enter a number to display its multiplication table: "))

print(f"\nMultiplication Table of {num}:")

for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

# 9.To write a Python program to calculate the factorial of a number using a loop.

num = int(input("Enter a number: "))

factorial = 1

if num < 0:
    print("Factorial does not exist for negative numbers.")
elif num == 0:
    print("The factorial of 0 is 1.")
else:
    for i in range(1, num + 1):
        factorial = factorial * i

    print(f"The factorial of {num} is {factorial}")

# 10. To write a Python program to find the sum of the first N natural numbers.

n = int(input("Enter a value for N: "))

if n <= 0:
    print("Please enter a positive integer greater than 0.")
else:
    total_sum = 0

    for i in range(1, n + 1):
        total_sum += i

    print(f"The sum of the first {n} natural numbers is: {total_sum}")

# 11. To write a Python program to print numbers from 1 to N using a for loop.

N = int(input("Enter the value of N: "))

for i in range(1, N + 1):
    print(i)

# 12. To write a Python program to print numbers in reverse order from N to 1.

N = int(input("Enter the value of N: "))

for i in range(N, 0, -1):
    print(i)

# 13. To write a Python program to print all even numbers up to a given limit.

limit = int(input("Enter the upper limit: "))

for i in range(2, limit + 1, 2):
    print(i)

# 14. To write a Python program to reverse the digits of a given number.

num = int(input("Enter an integer: "))

reversed_num = 0
original_num = abs(num)

while original_num > 0:
    remainder = original_num % 10
    reversed_num = (reversed_num * 10) + remainder
    original_num = original_num // 10

if num < 0:
    reversed_num = -reversed_num

print("Reversed number:", reversed_num)

# 15. To write a Python program to count the number of digits in a given integer.

num = int(input("Enter an integer: "))

count = 0
original_num = abs(num)

if original_num == 0:
    count = 1
else:
    while original_num > 0:
        original_num = original_num // 10
        count += 1

print(f"Total number of digits: {count}")

# 16. To write a Python program to calculate the sum of digits of a given number.

num = int(input("Enter a number: "))

digit_sum = 0

temp = abs(num)

while temp > 0:
    digit_sum += temp % 10
    temp //= 10

print(f"The sum of the digits is: {digit_sum}")

# 17. To write a Python program to check whether a given number is prime.

import math

num = int(input("Enter an integer: "))

is_prime = True

if num <= 1:
    is_prime = False
else:
    for i in range(2, int(math.isqrt(num)) + 1):
        if num % i == 0:
            is_prime = False
            break

if is_prime:
    print(f"{num} is a prime number.")
else:
    print(f"{num} is not a prime number.")

# 18. To write a Python program to generate the Fibonacci series up to N terms.

n = int(input("How many terms of the Fibonacci series do you want? "))

a, b = 0, 1
count = 0

if n <= 0:
    print("Please enter a positive integer greater than 0.")
elif n == 1:
    print(f"Fibonacci series up to {n} term:")
    print(a)
else:
    print(f"Fibonacci series up to {n} terms:")
    while count < n:
        print(a, end=" ")
        a, b = b, a + b
        count += 1
    print()

# 19. To write a Python program to check whether a string is a palindrome.

text = input("Enter a string: ")

reversed_text = text[::-1]

if text == reversed_text:
    print("The string is a palindrome.")
else:
    print("The string is not a palindrome.")

# 20. To write a Python program to check whether a given number is an Armstrong number.

def is_armstrong(num):

    num_str = str(num)
    num_digits = len(num_str)

    temp = num
    sum_of_powers = 0

    while temp > 0:
        digit = temp % 10
        sum_of_powers += digit ** num_digits
        temp //= 10

    return sum_of_powers == num

user_input = int(input("Enter a number: "))

if is_armstrong(user_input):
    print(f"{user_input} is an Armstrong number!")
else:
    print(f"{user_input} is not an Armstrong number.")